micronaut:
  application:
    name: keymanagerRest

grpc:
  client:
    plaintext: true
    max-retry-attempts: 10
  channels:
    keyManager:
      address: ${KEY_MANAGER_ADDRESS:`localhost:50051`}

#datasources:
#  default:
#    url: ${DB_HOST:`jdbc:postgresql://localhost:5432/keymanager`}
#    username: ${DB_USER:root}
#    password: ${DB_PASS:Root@12345}
#    driverClassName: org.postgresql.Driver
#    dialect: POSTGRES
#jpa.default.properties.hibernate.hbm2ddl.auto: update

jackson.serialization.writeDatesAsTimestamps: false